Package/main/default/objects/UI_Job_Status__c/UI_Job_Status__c.object-meta.xml
<CustomObject>
    <label>UI Job Status</label>
    <nameField>
        <displayFormat>UJS{00000}</displayFormat>
        <label>UI Job Status Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UI Job Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UI_Job_Status__c/fields/Request_Id__c.field-meta.xml
<CustomField>
    <fullName>Request_Id__c</fullName>
    <externalId>true</externalId>
    <label>Request Id</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/UI_Job_Status__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/UI_Job_Status__c/fields/Task_Configuration_Id__c.field-meta.xml
<CustomField>
    <fullName>Task_Configuration_Id__c</fullName>
    <label>Task Configuration Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

Package/main/default/objects/UI_Task_Configuration__mdt/UI_Task_Configuration__mdt.object-meta.xml
<CustomObject>
    <label>UI Task Configuration</label>
    <pluralLabel>UI Task Configurations</pluralLabel>
</CustomObject>

force-app/main/default/classes/UIJobControllerTest.cls
@isTest
public without sharing class UIJobControllerTest {
              
    @isTest
    static void testUIJobController() {  
        String recordIdStr ='TestRecordId';
        String metaDataNameStr ='Test_Job';
        String lastString ='';
        UIJobTaskAbstract.ResultWrapper result = new UIJobTaskAbstract.ResultWrapper();
        UI_Job_Status__c jobStatus;
        UIJobController.initPage(recordIdStr, metaDataNameStr);
        
        Id successTaskId = [select id from UI_Task_Configuration__mdt Where DeveloperName = 'Test_Success_Sync'][0].id;
        Id failTaskId = [select id from UI_Task_Configuration__mdt Where DeveloperName = 'Test_Fail_Sync'][0].id;
        
        Id taskId = successTaskId;

        UIJobController.startTask(recordIdStr,taskId);
        jobStatus =[Select Id,Task_Configuration_Id__c,Request_Id__c,Status__c,Error_Message__c from UI_Job_Status__c where Request_Id__c =:recordIdStr][0];  
        System.AssertEquals('In Progress', jobStatus.Status__c , 'After Starting a Task,the status of Job is In Progress');

        UIJobController.endTask(recordIdStr,taskId,'');
        jobStatus =[Select Id,Task_Configuration_Id__c,Request_Id__c,Status__c,Error_Message__c from UI_Job_Status__c where Request_Id__c =:recordIdStr][0];  
        System.AssertEquals('In Progress', jobStatus.Status__c , 'No Error. The status of Job is In Progress');
        System.AssertEquals(taskId, jobStatus.Task_Configuration_Id__c , 'Task Id Should be set');
        
        UIJobController.endTask(recordIdStr,taskId,'Error Message');
        jobStatus =[Select Id,Task_Configuration_Id__c,Request_Id__c,Status__c,Error_Message__c from UI_Job_Status__c where Request_Id__c =:recordIdStr][0];  
        System.AssertEquals('Failed', jobStatus.Status__c , 'Error. The status of Job is Failed');
        System.AssertEquals('Error Message', jobStatus.Error_Message__c , 'Error Message should be set.'); 


        UIJobController.endSuccessJob( recordIdStr,successTaskId);
        jobStatus =[Select Id,Task_Configuration_Id__c,Request_Id__c,Status__c,Error_Message__c from UI_Job_Status__c where Request_Id__c =:recordIdStr][0];  

        System.AssertEquals('Success', jobStatus.Status__c , 'End Job is called, The status of job should be Success.');
        System.AssertEquals(true, String.isEmpty(jobStatus.Error_Message__c) , 'Error Message should be reset.');

        result = UIJobController.runServerTask(recordIdStr,successTaskId,'',true,lastString,false);
        result = UIJobController.runServerTask(recordIdStr,failTaskId,'',true,lastString,false);
        
        AsyncApexJob aaj;
        Test.startTest();
            result =  UIJobController.runQueueableServerTask(recordIdStr, metaDataNameStr,taskid,'',lastString);
            aaj =  UIJobController.checkQueueableStatus(result.JobId,recordIdStr,taskid);
            System.AssertEquals('Queued', aaj.Status , 'Job will be queued');
            jobStatus =[Select Id,Task_Configuration_Id__c,Request_Id__c,Status__c,Error_Message__c from UI_Job_Status__c where Request_Id__c =:recordIdStr][0];  
            System.AssertEquals('In Progress', jobStatus.Status__c , 'Error. The status of Job is In Progress');
            
        Test.stopTest();   
        aaj =  UIJobController.checkQueueableStatus(result.JobId,recordIdStr,taskid);  
        System.AssertEquals('Completed', aaj.Status , 'Job will be Completed');
        jobStatus =[Select Id,Task_Configuration_Id__c,Request_Id__c,Status__c,Error_Message__c from UI_Job_Status__c where Request_Id__c =:recordIdStr][0];  
        System.AssertEquals('In Progress', jobStatus.Status__c , 'No Error. The status of Job is In Progress');

            
    }
    @isTest
    static void testUIJobControllerQueueError() {  
        String recordIdStr ='TestRecordId';
        String metaDataNameStr ='Test_Job';
        String lastString ='';
        UI_Job_Status__c jobStatus;
        UIJobTaskAbstract.ResultWrapper result = new UIJobTaskAbstract.ResultWrapper();
        UIJobController.initPage(recordIdStr, metaDataNameStr);
        
        Id failTaskId = [select id from UI_Task_Configuration__mdt Where DeveloperName = 'Test_Fail_Sync'][0].id;
        AsyncApexJob aaj;
        try{
            Test.startTest();
                result = UIJobController.runQueueableServerTask(recordIdStr, metaDataNameStr,failTaskId,'',lastString);
                aaj =  UIJobController.checkQueueableStatus(result.JobId,recordIdStr,failTaskId);
                System.AssertEquals('Queued', aaj.Status , 'Job will be queued');
                jobStatus =[Select Id,Task_Configuration_Id__c,Request_Id__c,Status__c,Error_Message__c from UI_Job_Status__c where Request_Id__c =:recordIdStr][0];  
                System.AssertEquals('In Progress', jobStatus.Status__c , 'The status of Job is In Progress');          
            Test.stopTest();   
        }catch(Exception e)
        {
            System.assert(true,'Error Case');
        }

       
            
    }
}